// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlbupuirfleznpnhbmqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsYnVwdWlyZmxlem5wbmhibXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Nzk0MzUsImV4cCI6MjA2NjE1NTQzNX0.vSO7hXtL0S6ZTPfmDsBC8UmXr9yD5eo2G5eQBY2uNDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);